[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Unlike create-react-app, we don't need this redirect as Next.js handles routing differently
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
